apiVersion: v1
entries:
  restapi:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-09-24T17:15:00.858474027Z"
    description: A Helm chart for Kubernetes
    digest: 1cc871d2b8c0abc1d8d649fdb6c524c4f44896c88627df369659be8bbd0c995a
    name: restapi
    type: application
    urls:
    - restapi-0.1.0.tgz
    version: 0.1.0
generated: "2021-09-24T17:15:00.857722319Z"
